"""

Backend/Core - 

DEFINE - FINDING AND FINDINGSET SCHEMES USING PYDANTIC.
This Ensures that no matter which tool generates the report, 
the rest of the pipeline (Scoring, Aggregator, FrontEnd)
receives a consistent object.

"""

from pydantic import BaseModel, Field
from typing import List, Optional, Dict, Any
from enum import Enum

# a list of options for how dangerous a bug is
class Severity (str,Enum):
    CRITICAL = "Critical"
    HIGH = "High"
    MEDIUM = "Medium"
    LOW = "Low"
    INFORMATIONAL ="Informational"
    OPTIMIZATION = "Optimization"

# PASSPORT of a Bug
# If the tool tries to send a file without a file_path, it will throw an error.


class Finding(BaseModel):
    """
    Common format for security Discovery.
    """
    title: str = Field(... , description="Short name of the Vulnerability")
    description: str = Field(... , description="Detailed Explanation")
    severity: Severity = Field(... , description="Impact Level")
    tool: str = Field(... , description="Tool name (Slither, Mythril, Echidna)")

    #Location is flexible

    file_path: str
    line_number: List[int]
    # Raw output in case we need extra tool-specific data later
    raw_tool_output: Optional[Dict[str, Any]] = None


"""
Bucket for all finding  discovered in one smart contract.
Aggregator [takes all the output] ----> and Send them to the Front-End.
We Send a'Bucket of all findings' ==> FindingSet Object

"""
class FindingSet(BaseModel):
    target_file: str = Field(..., description="The path of the smart contract that was analyzed")
    findings: List[Finding] = Field(default_factory=list, description="The list of findings generated by the tools")
    metadata: Optional[Dict[str,Any]] = Field(
        default_factory=dict,
        description="Optional metadata such as scan duration, tool versions, or environment details"
    )